# Generated by Django 4.1.5 on 2023-02-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_category_service', '0002_alter_productcategory_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('price', models.CharField(blank=True, max_length=8, null=True)),
                ('desc', models.CharField(blank=True, max_length=155, null=True)),
                ('mfg_date', models.CharField(blank=True, max_length=35, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_category_service.productcategory')),
            ],
        ),
    ]
