# Generated by Django 4.1.5 on 2023-02-03 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUsers',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=555, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 8, 46, 5, 140872, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthProvider.businessusers')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 8, 46, 5, 141872, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthProvider.businessusers')),
            ],
        ),
    ]
