# Generated by Django 4.1.5 on 2023-02-03 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthProvider', '0002_alter_businessusers_created_at_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessusers',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 13, 51, 5, 753150, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='businessusers',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 13, 51, 5, 754146, tzinfo=datetime.timezone.utc)),
        ),
    ]
