# Generated by Django 4.1.5 on 2023-02-03 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthProvider', '0004_remove_otp_id_remove_refreshtoken_userid_otp_otp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessusers',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 14, 20, 33, 102746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='businessusers',
            name='uid',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 3, 14, 20, 33, 102746, tzinfo=datetime.timezone.utc)),
        ),
    ]
