# Generated by Django 4.1.5 on 2023-02-04 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthProvider', '0006_remove_otp_otp_id_alter_businessusers_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='token_id',
        ),
        migrations.AlterField(
            model_name='businessusers',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 4, 16, 49, 31, 271865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 4, 16, 49, 31, 272862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AuthProvider.businessusers'),
        ),
    ]
