# Generated by Django 4.1.5 on 2023-02-08 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_auth_service', '0004_alter_businessusers_created_at_alter_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=35, null=True)),
                ('brand_desc', models.CharField(blank=True, max_length=155, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 8, 7, 24, 1, 637369, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_auth_service.businessusers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=35, null=True)),
                ('desc', models.CharField(blank=True, max_length=155, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 8, 7, 24, 1, 637369, tzinfo=datetime.timezone.utc))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_brandCategoryProduct_service.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('price', models.CharField(blank=True, max_length=8, null=True)),
                ('desc', models.CharField(blank=True, max_length=155, null=True)),
                ('mfg_date', models.CharField(blank=True, max_length=35, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_brandCategoryProduct_service.productcategory')),
            ],
        ),
    ]
