# Generated by Django 4.1.5 on 2023-02-10 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brandCategoryProduct_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 10, 13, 25, 23, 928257, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 10, 13, 25, 23, 929264, tzinfo=datetime.timezone.utc)),
        ),
    ]
