# Generated by Django 4.1.5 on 2023-02-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_production_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='product_number',
            new_name='production_rate',
        ),
    ]
