# Generated by Django 4.1.5 on 2023-02-06 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_brands_service', '0002_alter_brand_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=35, null=True)),
                ('desc', models.CharField(blank=True, max_length=155, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 6, 8, 34, 3, 193296, tzinfo=datetime.timezone.utc))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_brands_service.brand')),
            ],
        ),
    ]
