# Generated by Django 4.1.5 on 2023-02-06 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_category_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 6, 8, 34, 26, 422198, tzinfo=datetime.timezone.utc)),
        ),
    ]
