# Generated by Django 4.1.5 on 2023-02-11 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0005_alter_businessusers_created_at_alter_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created_at',
            new_name='expiry',
        ),
        migrations.AlterField(
            model_name='businessusers',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 11, 6, 42, 26, 150016, tzinfo=datetime.timezone.utc)),
        ),
    ]
