# Generated by Django 4.1.5 on 2023-02-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_brandCategoryProduct_service', '0005_alter_brand_created_at_and_more'),
        ('micro_auth_service', '0007_alter_businessusers_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('stock_quantity', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='micro_brandCategoryProduct_service.product')),
                ('stock_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_auth_service.businessusers')),
            ],
        ),
    ]
