# Generated by Django 4.1.5 on 2023-02-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0009_alter_businessusers_created_at'),
        ('micro_brandCategoryProduct_service', '0006_alter_brand_created_at_and_more'),
        ('micro_business_service', '0002_alter_stock_stock_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='imported_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='imported_from', to='micro_auth_service.businessusers'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='micro_brandCategoryProduct_service.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stock_admin', to='micro_auth_service.businessusers'),
        ),
    ]
