# Generated by Django 4.1.5 on 2023-02-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0011_alter_businessusers_created_at'),
        ('micro_brandCategoryProduct_service', '0008_alter_brand_created_at_and_more'),
        ('micro_business_service', '0004_productpriceforwholesalerandretailer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPriceForWholesalerAndRetailer',
            new_name='SetProductPriceForWholesalerAndRetailer',
        ),
    ]
