# Generated by Django 4.1.5 on 2023-02-06 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_auth_service', '0002_alter_businessusers_created_at_alter_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=35, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 6, 8, 33, 0, 390385, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_auth_service.businessusers')),
            ],
        ),
    ]
