# Generated by Django 4.1.5 on 2023-02-06 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brands_service', '0002_alter_brand_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_desc',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 6, 9, 2, 2, 174497, tzinfo=datetime.timezone.utc)),
        ),
    ]
